import subprocess
import random
import shutil
import os
import math

# parameter ranges for random search
param_ranges = {
    'pos_cost_weight': (50, 500),
    'vel_cost_weight': (0, 200),
    'delta_cost_weight': (10, 100),
    'collision_cost_weight': (1e5, 1e8),
    'obstacle_eps': (0.1, 1.0),
    'Sigma00': (0.01, 0.5),
    'Sigma11': (10.0, 500.0),
    'lambda': (0.1, 5.0),
    'N': (20, 100)
}

runs = 30
best_cost = float('inf')
best_params = None

base_cfg = 'mppi.cfg'

def write_cfg(params):
    with open(base_cfg, 'w') as f:
        f.write('# autogenerated by tuner\n')
        for k,v in params.items():
            f.write(f"{k} {v}\n")

for i in range(runs):
    # sample parameters
    params = {}
    for k,(lo,hi) in param_ranges.items():
        if isinstance(lo, int) and isinstance(hi, int):
            params[k] = random.randint(lo, hi)
        else:
            params[k] = random.uniform(lo, hi)
    write_cfg(params)

    print(f"run {i+1}/{runs}: {params}")
    # run simulation
    try:
        # allow more time for slower parameter sets
        # on Windows the exe can be invoked without "./"
        output = subprocess.check_output(['vehicle_sim.exe'], stderr=subprocess.STDOUT, text=True, timeout=60)
    except subprocess.CalledProcessError as e:
        print("simulation failed, output was:\n", e.output)
        continue
    except subprocess.TimeoutExpired as e:
        print("simulation timeout (after 60s). partial output:\n", e.output)
        continue

    # parse total_cost
    total_cost = None
    for line in output.splitlines():
        if line.startswith('total_cost='):
            total_cost = float(line.split('=')[1])
            break
    if total_cost is None:
        print("no cost reported, skipping")
        continue

    print("-> cost", total_cost)
    if total_cost < best_cost:
        best_cost = total_cost
        best_params = params.copy()
        shutil.copy(base_cfg, 'best.cfg')

print("best", best_cost, best_params)
print("best.cfg written")
